tools:
    php_analyzer:                true
    php_sim:                     true
    php_changetracking:          true
    php_cs_fixer:                true
    php_mess_detector:           true
    php_code_sniffer:            true
    php_pdepend:                 true
    sensiolabs_security_checker: true
